In [18]:
path= 'N:\\TESE\\Bullwhip\\data\\results'

import os 
import pandas as pd

In [ ]:

for dir in os.listdir(path):
    if 'sim_' in dir:
        # print(dir)
        for file in os.listdir(os.path.join(path, dir)):
            if 'inventory_actor_0' in file:
                with open(os.path.join(path, dir, file), 'r') as f:
                    lines = f.readlines()
                    print( f"{file[:-4]} -> {lines[-1][44:-4]}","\n")

In [ ]:
mega_csv=""

for dir in os.listdir(path):
    if 'sim_' in dir:
        # print(dir)
        for file in os.listdir(os.path.join(path, dir)):
            if 'transactions_closed' in file:
                with open(os.path.join(path, dir, file), 'r') as f:
                    lines = f.readlines()
                    
                    for line in lines:
                        # print(line)
                        # line = line.replace("'", '"')
                        line = line.replace(" ", '')
                     
                        line = line.replace("{'deliver_day':", '')
                        line = line.replace("'order_id':", '')
                        line = line.replace("'order_criation_day':", '')
                        line = line.replace("'sending_day':", '')
                        line = line.replace("'receiver':", '')
                        line = line.replace("'sender':", '')
                        line = line.replace("'product':", '')
                        line = line.replace("'quantity':", '')
                        line = line.replace("'delitransit_timever_day':", '')
                        line = line.replace("'lead_time':", '')
                        line = line.replace("'theoretical_lead':", '')
                        line = line.replace("'update_day':", '')
                        line = line.replace("'transaction_id':", '')
                        line = line.replace("'delivered':", '')
                        line = line.replace("'transit_time':", '')
                        line = line.replace("},", f",{file[-10:-4]}")
                    
                        # line = line.replace(",", ':')
                        # line = line.split(":")
                        # mega_csv+=line
                        
                        # z= line.split(",")
                        # z=[eval(i) for i in z]
                        mega_csv+=line
                        # print(f"d>{line}<")


    
with open("N:\\TESE\\Bullwhip\\data\\results\\mega_csv.csv", 'w') as f:
    f.write(mega_csv)

In [72]:
cols = ['deliver_day','order_id','order_criation_day','sending_day','receiver','sender','product','quantity','transit_time','lead_time','theoretical_lead','update_day','transaction_id','delivered', "file"]

t= pd.read_csv("N:\\TESE\\Bullwhip\\data\\results\\mega_csv.csv", sep=",", names=cols, index_col=False)
t

,deliver_day,order_id,order_criation_day,sending_day,receiver,sender,product,quantity,transit_time,lead_time,theoretical_lead,update_day,transaction_id,delivered,file
0,6,1000001,1,1,0,1,1001,10090,5,5,5,6,1,1,190206
1,8,1000002,2,2,0,1,1001,10305,6,6,6,8,2,1,190206
2,9,1000003,3,3,0,1,1001,10368,6,6,6,9,3,1,190206
3,9,1000004,4,4,0,1,1001,10388,5,5,5,9,4,1,190206
4,10,1000005,5,5,0,1,1001,10284,5,5,5,10,5,1,190206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160829,5739,5005738,5738,5738,4,5,5001,16954,1,2,1,5740,51638,1,194522
160830,5740,6005738,5738,5738,5,6,6001,16954,2,2,2,5740,51639,1,194522
160831,5740,7005738,5738,5738,6,7,7001,16954,2,2,2,5740,51640,1,194522
160832,5739,8005738,5738,5738,7,8,8001,16954,1,2,1,5740,51641,1,194522
160833,5739,9005738,5738,5738,8,9,9001,16954,1,2,1,5740,51642,1,194522